### ISSUE TITLE
M loads code in Rails development mode 

### ISSUE THREAD

**Issue by josephbhunt** [qrush/m#63] opened 2016-09-23 15:13 UTC
I have something like this in a Rails project
`@thing = Rails.env.test? ? ThingThing : OtherThing`

When M loads this source file `Rails.env` returns `"development"`. Shouldn't is return `"test"`?
This causes tests to fail using M (`m path_to_file:line_number`). but they pass using MiniTest (`rake test path_to_file`).

I've tried running `m path_to_file:line_number RAILS_ENV=test`. Still no luck.

**Comment by zamith** [comment] 2016-09-26 12:55
`m` does not use or change the Rails environment. Are you setting the `RAILS_ENV` to test in your test helper file?

Also, is the app or a smaller version where the error can be reproduced available publicly anywhere?

**Comment by zamith** [comment] 2016-11-06 11:25
I'm closing this until we have more details.

**Closed by zamith** 2016-11-06 11:25 UTC

**Comment by Chrisly3ear** [comment] 2017-07-07 21:11
It also overwrites my development DB every time I run a test using a line number. Pretty annoying.

**Comment by zamith** [comment] 2017-07-07 23:29
@Chrisly3ear Which test runner are you using? Minitest? If so, which version? 

M only wraps around your test runner, it should not in any way affect your database or environment.

**Comment by Chrisly3ear** [comment] 2017-07-08 11:09
I'm running 

- ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
- Rails 5.1.2
- minitest-reporters 1.1.14
- m 1.5.1

In my test_helper.rb I have
`require "minitest/reporters"
Minitest::Reporters.use! Minitest::Reporters::SpecReporter.new`

- If I do "rake", all tests run and the dev environment stays intact. 
- If I do "m" without any arguments, the dev environment also stays intact.
- But if I do "m test\models\some_model_test.rb:18" to run a specific test, the dev environment is cleared, and only the test fixtures remain in the DB.

Am I doing this wrong or is there a problem with "m"?

All the best,
Chris

**Comment by zamith** [comment] 2017-07-08 11:32
Is your app somewhere public, or do you have a small example I can use to test? I find it very hard to believe that it would be `m` doing anything wrong, because it should just parse your spec files and tell the specific test runner which tests to run, it doesn't really run anything.

That being said, for Rails 5 you can actually also run `rails test test\models\some_model_test.rb:18` and it should work.

**Comment by Chrisly3ear** [comment] 2017-07-08 11:42
Hey @zamith, thanks for replying so quickly!

You can have a look at the project and the test I'm running here: https://github.com/Chrisly3ear/learning_rails_5/blob/master/test/models/user_test.rb#L18

I'm just getting into Rails by following a comprehensive tutorial series. So I'm in no way an expert and the problem could easily lie somewhere else. My guess was the `m` gem, because this problem occured right after using it for the first time.

As I said: Maybe I'm doing something wrong. I definitely don't want to waste anyones time, so I'll probably use the `rails test` command. I just tried it and I couldn't observe the effects that occured using the `m` command.

Chris
