### ISSUE TITLE
Run directly if no line number specified

### ISSUE THREAD

**Issue by Paxa** [qrush/m#55] opened 2016-03-11 10:00 UTC
I try to use `m` with spring and it takes extra 3-4 seconds compare if I run tests directly

If no line number specified require file directly and it will work fater

**Comment by zamith** [comment] 2016-03-11 14:56
If no arguments are passed, `m` shells out to `rake test`, no parsing at all is done. The only price you pay is of loading `m` into memory. 

What exact commands are you comparing?

**Comment by Paxa** [comment] 2016-03-11 16:16
Original:
```ruby
require 'm'
M.run(ARGV)
```

Faster:
```ruby
Dir.glob('./test/**/*_spec.rb').each do |file|
    require file
end
```

**Comment by zamith** [comment] 2016-03-11 16:46
Right, but how are you running this? Are you using `rake` on both situations?

**Comment by Paxa** [comment] 2016-03-11 16:52
I try to use `spring-commands-m`, generate binstub and then try to change it little.

Currently it looks like this:
```ruby
#!/usr/bin/env ruby
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError => e
  raise unless e.message.include?('spring')
end

require_relative '../config/boot'

#require 'm'
#load Gem.bin_path('m', 'm')

Dir.glob('./test/**/*_spec.rb').each do |file|
  if ARGV[0]
    require file if file.include?(ARGV[0])
  else
    require file
  end
end
```

**Comment by Paxa** [comment] 2016-03-11 16:53
It's easier to type `m filename` then `take test FILE=filename`

**Comment by zamith** [comment] 2016-03-11 17:21
The reason I'm asking is that running `rake` is not super fast. I'll take a look at this and see if there's way we can make this faster.

**Comment by zamith** [comment] 2019-05-27 16:46
Cannot reproduce this, closing the issue. If it is still a problem, please open again.

**Closed by zamith** 2019-05-27 16:46 UTC
